### ISSUE TITLE
set power_limit AssertionError

### ISSUE THREAD

**Issue by LinusChen-yf** [agoose77/throttlestop#12]
~  sudo throttlestop tdp                                                                                          1 err | 14:30:42 
```
{
    "MSR_PKG_POWER_LIMIT": 18722037335687528,
    "first": {
        "MSR_PKG_POWER_LIMIT": 18722037335687528,
        "power_limit": 45.0,
        "power_enabled": true,
        "power_clamping_limit": true,
        "power_limit_time_window": 28.0,
        "__types.SimpleNamespace": true
    },
    "second": {
        "MSR_PKG_POWER_LIMIT": 4359064,
        "power_limit": 115.0,
        "power_enabled": true,
        "power_clamping_limit": false,
        "power_limit_time_window": 0.00244140625,
        "__types.SimpleNamespace": true
    },
    "lock": false,
    "__types.SimpleNamespace": true
}
```

 ~  sudo throttlestop tdp "{\"first\": {\"power_limit\": 65.0}}"                                                      ok | 14:30:50 
```
Traceback (most recent call last):
  File "/usr/bin/throttlestop", line 8, in <module>
    sys.exit(main())
  File "/usr/lib/python3.10/site-packages/throttlestop/__main__.py", line 53, in main
    result = build_MSR_PKG_POWER_LIMIT(power_limits, units)
  File "/usr/lib/python3.10/site-packages/throttlestop/msr.py", line 96, in build_MSR_PKG_POWER_LIMIT
    result = _build_MSR_PKG_POWER_LIMIT_internal(_obj.first, _units, _max_power_limit)
  File "/usr/lib/python3.10/site-packages/throttlestop/msr.py", line 107, in _build_MSR_PKG_POWER_LIMIT_internal
    assert 0. <= _obj.power_limit <= _max_power_limit, _obj.power_limit
AssertionError: 65.0
```
I don't quite understand why this assertion fails, my cpu max tdp is 115w.
Hope you can help me look at this problem in your busy schedule, thanks in advance!

**Comment by azidanit** [comment]
after reading the code at /usr/lib/python3.10/site-packages/throttlestop/msr.py line 94.
I changed the from  `_max_power_limit=60` to `_max_power_limit=90` make sure to know you processor TDP

```
def build_MSR_PKG_POWER_LIMIT(_obj, _units, _max_power_limit=60):
    assert isinstance(_obj.lock, bool)
    result = _build_MSR_PKG_POWER_LIMIT_internal(_obj.first, _units, _max_power_limit)
    result |= _build_MSR_PKG_POWER_LIMIT_internal(_obj.second, _units, _max_power_limit) << 32
    result |= int(_obj.lock) << 63
    return result
```

you can use nano or vim to change the file

**Comment by LinusChen-yf** [comment]
I see why, thank you.
I shouldn't have looked at the code carefully at that time.
