### ISSUE TITLE
Failed to Start

### ISSUE THREAD

**Issue by user987098** [agoose77/throttlestop#13]
I'm sure that MSR is installed and enabled, I've tried the way it suggests, and different ways of enabling it but nothing has worked yet. (yes, I've rebooted everytime)

When installing and attempting to run the service I encounter this error:

`journalctl -xeu throttlestop.service            
░░ 

░░ A start job for unit throttlestop.service has finished with a failure.

░░ 
░░ The job identifier is 3460 and the job result is failed.

Aug 26 17:00:49 Purp systemd[1]: Starting throttlestop.service - throttlestop...

░░ Subject: A start job for unit throttlestop.service has begun execution

░░ Defined-By: systemd

░░ Support: https://www.debian.org/support

░░ 
░░ A start job for unit throttlestop.service has begun execution.

░░ 

░░ The job identifier is 3571.

Aug 26 17:00:49 Purp python3[7120]: Traceback (most recent call last):

Aug 26 17:00:49 Purp python3[7120]:   File "<frozen runpy>", line 198, in _run_module_as_main

Aug 26 17:00:49 Purp python3[7120]:   File "<frozen runpy>", line 88, in _run_code

Aug 26 17:00:49 Purp python3[7120]:   File "/usr/local/lib/python3.11/dist-packages/throttlestop/__main__.py", line 96, in 
<module>

Aug 26 17:00:49 Purp python3[7120]:     main()

Aug 26 17:00:49 Purp python3[7120]:   File "/usr/local/lib/python3.11/dist-packages/throttlestop/__main__.py", line 42, in 
main

Aug 26 17:00:49 Purp python3[7120]:     msr.validate_install(test_address=MSR_VOLTAGE_ADDR)

Aug 26 17:00:49 Purp python3[7120]:   File "/usr/local/lib/python3.11/dist-packages/throttlestop/msr.py", line 52, in validate_install

Aug 26 17:00:49 Purp python3[7120]:     raise RuntimeError("rdmsr call failed. Have you loaded the msr module with 
modprobe msr?")

Aug 26 17:00:49 Purp python3[7120]: RuntimeError: rdmsr call failed. Have you loaded the msr module with modprobe msr?

Aug 26 17:00:49 Purp systemd[1]: throttlestop.service: Main process exited, code=exited, status=1/FAILURE`

**Comment by Matiasgamerss456** [comment]
i'm having the same problem and i don't know what to do or why it's happening, i already tried modprobe msr a lot of times, ive enabled it, i also enabled throttlestop.timer and it worked, but the thing that keeps failing is throttlestop.service and trying to do rdmsr

**Comment by Matiasgamerss456** [comment]
wait, i think my cpu just cant undervolt
