### ISSUE TITLE
SyntaxError: invalid syntax

### ISSUE THREAD

**Issue by dreamcat4** [agoose77/throttlestop#2]
Not sure why this happen, maybe because the system python is not compatible? Here is my environment:

```sh
$ which python
/usr/bin/python
[id:~/.dev] $ python --version
Python 2.7.15+
[id:~/.dev] $ lsb_release -a
LSB Version:	core-9.20170808ubuntu1-noarch:printing-9.20170808ubuntu1-noarch:security-9.20170808ubuntu1-noarch
Distributor ID:	Ubuntu
Description:	Ubuntu 18.10
Release:	18.10
Codename:	cosmic
[id:~/.dev] $ uname -a
Linux apex 5.0.7-050007-lowlatency #201904052141 SMP PREEMPT Fri Apr 5 21:45:46 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
[id:~/.dev] $ 
```

The error output was as follows:

```sh
$ sudo pip install git+https://github.com/agoose77/throttlestop.git#egg=throttlestop
The directory '/home/id/.cache/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
The directory '/home/id/.cache/pip' or its parent directory is not owned by the current user and caching wheels has been disabled. check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
Collecting throttlestop from git+https://github.com/agoose77/throttlestop.git#egg=throttlestop
  Cloning https://github.com/agoose77/throttlestop.git to /tmp/pip-build-jRaH8I/throttlestop
Requirement already satisfied: numpy in /home/id/.local/lib/python2.7/site-packages (from throttlestop)
Collecting plumbum (from throttlestop)
  Downloading https://files.pythonhosted.org/packages/48/48/0c592a65c8ecc6a4c0da41d75097704a283595b6731be1531eee3f4f7778/plumbum-1.6.7-py2.py3-none-any.whl (110kB)
    100% |████████████████████████████████| 112kB 1.2MB/s 
Installing collected packages: plumbum, throttlestop
  Running setup.py install for throttlestop ... done
Successfully installed plumbum-1.6.7 throttlestop-0.0.2
[id:~/.dev] $ throttlestop
Traceback (most recent call last):
  File "/usr/local/bin/throttlestop", line 11, in <module>
    load_entry_point('throttlestop==0.0.2', 'console_scripts', 'throttlestop')()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 484, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2707, in load_entry_point
    return ep.load()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2325, in load
    return self.resolve()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2331, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/local/lib/python2.7/dist-packages/throttlestop/__main__.py", line 10
    def apply_delta(delta: dict, ns: SimpleNamespace):
                         ^
SyntaxError: invalid syntax
[id:~/.dev] 1 $ throttlestop
throttlestop                  throttlestop-install-service  
[id:~/.dev] 1 $ throttlestop --help
Traceback (most recent call last):
  File "/usr/local/bin/throttlestop", line 11, in <module>
    load_entry_point('throttlestop==0.0.2', 'console_scripts', 'throttlestop')()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 484, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2707, in load_entry_point
    return ep.load()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2325, in load
    return self.resolve()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2331, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/local/lib/python2.7/dist-packages/throttlestop/__main__.py", line 10
    def apply_delta(delta: dict, ns: SimpleNamespace):
                         ^
SyntaxError: invalid syntax
[id:~/.dev] 1 $ 
```

**Comment by agoose77** [comment]
Hi,

Those type annotations are Py3 only, and it seems that for some reason pip2 is picking it up anyway. I'll take a look.

**Comment by NikitaFeodonit** [comment]
It works for me:
```
sudo apt-get install python3-pip
pip3 install git+https://github.com/agoose77/throttlestop.git#egg=throttlestop
```

**Comment by dreamcat4** [comment]
@NikitaFeodonit thank you that worked!!

Also to remove / reverse the previous broken 2.7 version, from system path:

```sh
sudo pip uninstall git+https://github.com/agoose77/throttlestop.git#egg=throttlestop
```

@agoose77 so it was the python version then. I shall leave you to close this issue. In case there is anything else to be done...

For example if you cannot fix this tool to be compatible on other versions of python, then you might instead just be changing the installation instructions in the `README.md` file. To make them more comprehensive and show how to do `pip3` install instead. Or just say... 'this tool requires python3'. Well whatever. Just glad to be able to use it on ubuntu. Kind Regards.

**Comment by agoose77** [comment]
Apologies, I pushed the fixed annotations but didn't reply here. Really I should put the module on PyPI, and go into more depth on the readme. This tool is mainly here for me to reinstall on my Dell Latitude when I need, as the thermals are very poor.
